### ISSUE TITLE
4xx error handling

### ISSUE THREAD

**Issue by dsebastien** [solid/solid-architecture#4]
Just an idea that popped while i was reading https://github.com/solid/solid-architecture/blob/master/server/request-flow.md.

https://tools.ietf.org/html/rfc7807 is pretty neat to standardize/structure error messages returned to clients and make it easier for them to interpret/handle the error details.

In a recent project, we integrated it and we found it really beneficial. You can find some docs and examples here (we've gone a bit further than what the RFC initially covered):
* https://github.com/NationalBankBelgium/REST-API-Design-Guide/wiki/Error-handling-Error-details
* example: https://github.com/NationalBankBelgium/REST-API-Design-Guide/wiki/Error-handling-Example-with-multiple-errors
* other related docs: https://github.com/NationalBankBelgium/REST-API-Design-Guide/wiki/Error-handling-About

**Comment by RubenVerborgh** [comment]
Did you mean https://tools.ietf.org/html/rfc7807 ?

**Comment by csarven** [comment]
@RubenVerborgh  They use both RFCs AFAICT: https://github.com/NationalBankBelgium/REST-API-Design-Guide/wiki/Error-handling-Error-details#representation

**Comment by dsebastien** [comment]
Indeed rfc7807. I've picked the wrong link :)

**Comment by RubenVerborgh** [comment]
Indeed, seems like a good idea; I would just slap a JSON-LD context on there (and do conneg so we can have it in multiple formats).
